### ISSUE TITLE
Youtube video previews do not get loaded. 

### ISSUE THREAD

**Issue by maikelthedev** [vmstan/vmstio#16]
### Please describe the issue you are seeing.

1. Are you seeing error codes? If so please include the full error message and,
if it makes sense to, a screenshot.
2. When are you seeing the issue? When you are submitting posts? Uploading media?

This video never preloads from this instance but yes from many others (mastodon.london, toots.maikel.dev, mastodonapp.uk) with different versions of Mastodon (v.4.1.0, v.4.0.1, v.4.0.2)

https://youtu.be/AJWtLf4-WWs

This other video neither

https://www.youtube.com/watch?v=CduA0TULnow

If the issue is fixed for those two links it shouldn't happen again with any other future links. But so far it seems to be random with some video links. As shown to @vmstan the same video linked different (e.g.: a cut of the video gaming youtube sharing links) does show the preview so it's not the video itself, it's the links. 

This might require asking Masto-team who does the prefetch of video previews and when since they have such wonderful documentation where this isn't mentioned at all. 

This just gives a slightly degraded UX because we worked out a way to fetch the previews but...other users who don't know this might be puzzled. I wouldn't either classify this as a priority. 

### When did you first notice this issue?

today

### What geographic region are you accessing vmst.io from?

spain

### What browsers and/or apps are you accessing vmst.io from?

firefox

### Do you get any specific error codes?

nope

### Is there anything else that we should know?

P is not NP.

**Comment by maikelthedev** [comment]
Dear Lord, am I the only person who ever dared to open an issue?

**Comment by vmstan** [comment]
Is this still an issue for you @maikelthedev with the improved previews of 4.2? If so I want to file a bug report with the main repo.

**Comment by maikelthedev** [comment]
They both seem to preload with no issues. I'd say feel free to close it and if we notice it happens with any other youtube video we can always reopen it. 

https://vmst.io/deck/@maikel/111257479148998367
