### ISSUE TITLE
Posts get stuck and do not load on Home timeline

### ISSUE THREAD

**Issue by djwfyi** [vmstan/vmstio#2]
### Please describe the issue you are seeing.

When browsing my home timeline, I will fairly often see the timeline get "stuck" at a particular post and not load anything further back.

Today, Jan 7, 2022, 4:58 pm Central Time, it is happening to me.
It won't scroll any further pack than posts from 4:12pm. 

I'll scroll down the Home timeline, and then there gets a point where it won't scroll any further. The page shows a Load More button. When I click it, the page goes through some kind of loading exercise, but no additional posts load.

Normally, when this happens, the page should load additional posts.

This happens in the default web interface.
I've noticed it on both Pop!_OS and MacOS, happening in both Firefox and Chromium (getting stuck to the to the same post).

This does not seem to affect the other timelines.

Hard refresh, clearing cache, restarting browser do not have any effect.

### When did you first notice this issue?

This has been happening pretty much the whole time I've used it.

### What geographic region are you accessing vmst.io from?

North America/USA

### What browsers and/or apps are you accessing vmst.io from?

Firefox, Chromium

### Do you get any specific error codes?

Sometimes 502, normally nothing

### Is there anything else that we should know?

@maikelthedev also reported this issue.

**Comment by maikelthedev** [comment]
Straight copy and paste from my toot:

[@vmstan](https://vmst.io/@vmstan) [@djwfyi](https://vmst.io/@djwfyi) I don't think it was for me alone, I think I'm just the only idiot that looked at it happening and wondered 😂 

In..let me check my old instance:
Administration -> Server Settings -> Content Retention

User archives are kept by default 7 days. I guess today those 7 days were over and hence the home tab cleared up, for everyone, maybe? I don't know, it's just a theory.

**Comment by maikelthedev** [comment]
it's only happened to me once though.

**Comment by djwfyi** [comment]
I'm only experiencing it on Mastodon's web interface.
I can access the full history fine on Fedilab or pinafore.social.

**Comment by vmstan** [comment]
Does this happen both in the standard and advanced view?

**Comment by maikelthedev** [comment]
I guess it does because I'm an advance view mode guy while Daryl is a standard view mode guy and it also happens to him.

**Comment by vmstan** [comment]
My current theory is it's related to a timeout I occasionally see to the backend Redis cache.

**Comment by vmstan** [comment]
I made a couple changes to the Web service this morning, replacing the Stunnel containers I was using with the native linux service. (I have to use secured connections to Digital Ocean's Redis servers, but Mastodon doesn't support that out of the box so it has to tunnel through Stunnel) Not 100% that I'll fix it but let me know if you continue to see it.

**Comment by vmstan** [comment]
When it gets into this state, do new posts still come in at the top of the timeline, or is it just totally frozen?

Do other views in the advanced view like replies and such still refresh?

**Comment by maikelthedev** [comment]
New posts come but older posts are completely unnacessible.

**Comment by vmstan** [comment]
I have totally rebuilt the web nodes from scratch and am no longer using the Docker images on there, to make it at least a little easier to troubleshoot but also to bypass anything there. I've already moved away from Docker for almost anything else core to Mastodon because I was seeing issues on the Sidekiq side where it was just burning CPU. Let me know if you still see the issue.
