### ISSUE TITLE
login

### ISSUE THREAD

**Issue by clarker77** [vmstan/vmstio#28]
### What is your question?

Although I seem to be automatically logged in when I select sign in I'm told that some combination of E-mail address and password is incorrect. Attempts at resetting have yet to receive a response.

**Comment by vmstan** [comment]
What's your vmst.io username?

**Comment by clarker77** [comment]
It might be   clarker77

**Comment by clarker77** [comment]
@clarker

**Comment by vmstan** [comment]
Do me a favor and send me an email to vmstan@vmst.io from the registered email account.

**Comment by vmstan** [comment]
Actually I've sent a password reset email from the system to the registered address, and it's showing in the Mailgun logs as delivered.

**Comment by vmstan** [comment]
Resolved via email
