### ISSUE TITLE
matrix.vmst.io CORS error

### ISSUE THREAD

**Issue by vmstan** [vmstan/vmstio#78]
I have this issue on mobile as well. However, when I try to log into the web app and cross-sign as a workaround, it reports "Unable to query secret storage status", then quits the settings page. I seem to be unable to set up secure keys.

Using Firefox, connecting to matrix.vmst.io.

Update: Could this be due to a CORS error, perhaps a misconfiguration of the server?

![image](https://github.com/vector-im/element-android/assets/129/9de7e0bb-5956-4849-9303-4490df906d80)

_Originally posted by @canadaduane in https://github.com/vector-im/element-android/issues/6490#issuecomment-1741874826_

**Comment by canadaduane** [comment]
Looks like this is still happening, unfortunately:

![image](https://github.com/vmstan/vmstio/assets/129/536ed5bf-541f-4a90-b489-ed88ad61333c)

"Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://matrix.vmst.io/_matrix/client/v3/room_keys/version. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 404."

![image](https://github.com/vmstan/vmstio/assets/129/2ed9c3e6-1885-4a29-9302-7d84708a4528)

**Comment by canadaduane** [comment]
To replicate, just go Gear Icon -> All Settings -> Security & Privacy -> Set Up Secure Backup

**Comment by vmstan** [comment]
I wonder if this is related to the issues I'm having posting with Element X 🤔

**Comment by canadaduane** [comment]
Still seeing the same thing:

![image](https://github.com/vmstan/vmstio/assets/129/15174917-535e-41b2-b41a-9092eaf9ec4c)
