### ISSUE TITLE
October 9 Outage

### ISSUE THREAD

**Issue by djwfyi** [vmstan/vmstio#79]
### Please describe the issue you are seeing.

1. Are you seeing error codes? If so please include the full error message and,

503 errors for vmst.io. Status shows that vmst, federation API, streaming, and Matrix are all down.

3. When are you seeing the issue? When you are submitting posts? Uploading media?
Just trying to access services

### When did you first notice this issue?

Status shows since 2am Monday Oct 9 2023

### What geographic region are you accessing vmst.io from?

USA

### What browsers and/or apps are you accessing vmst.io from?

Firefox, Element, tusky, Megalodon

### Do you get any specific error codes?

503

### Is there anything else that we should know?

We are down across many services.

**Comment by vmstan** [comment]
http://status.digitalocean.com/incidents/fsfsv9fj43w7

**Comment by vmstan** [comment]
I'm attempting to get a temporary outage page on vmst.io but the DNS change is taking a bit.

**Comment by vmstan** [comment]
Messages sent out through Patreon, Kofi and Open Collective

> I slept very well last night, unfortunately when I got out of bed I learned there was blast crater where our Mastodon instance used to be.
> 
> Our hosting provider, Digital Ocean, is experiencing a massive outage of their entire managed Kubernetes service. We use this service for our entire application, web and backend processing layer for Mastodon and Matrix. They are down across all their regions currently with no ETA. https://status.digitalocean.com/incidents/fsfsv9fj43w7
> 
> Our persistent data, like the Postgres database and media uploads do not run in Kubernetes and are unaffected, and we anticipate no data loss issues overall.
> Please follow https://status.vmst.io and or https://github.com/vmstan/vmstio/issues/79 for more information.

**Comment by vmstan** [comment]
We are currently online with minimal functionality after I stood up a single web frontend to start processing UI and federation traffic.

Elasticsearch is currently offline. The streaming API is currently offline. Matrix is currently offline.

Timelines will be impacted while federated data is delivered and processed.

The outage started at approximately 0150 UTC on October 9. We didn't return to our  semi-functional state until 1520 UTC, which means there are roughly 14 hours worth of federated data waiting to be delivered from other instances.

This outage is also impacting other instances who use the Digital Ocean Kubernetes service, and have not yet even partially recovered.

**Comment by vmstan** [comment]
![CleanShot 2023-10-09 at 11 13 21@2x](https://github.com/vmstan/vmstio/assets/3002053/55012098-df40-4f7b-b62e-f68698f89be7)

Everything is being processed by a single VM, with 16 dedicated cores, and it's chewing them all up to get the backlog handled.

**Comment by vmstan** [comment]
Our streaming API should be back online, so the web interface will feel less clunky.

**Comment by vmstan** [comment]
### What's up?

- Mastodon API/UI
- Streaming API
- Sidekiq (backend processing)

### What's down?

- Matrix Synapse
- Matrix Sliding Sync
- Elasticsearch
- Libretranslate

### What was up, but broken, and now works

- Elk
- Semaphore

### What is up, but broken

- Element

### What was never impacted

- Documentation

**Comment by vmstan** [comment]
https://status.digitalocean.com/incidents/fsfsv9fj43w7 has an update:

> Our Engineering team has continued to investigate this issue but unfortunately, have not been able to determine a root cause for why worker nodes are entering the not-ready state unexpectedly. Attempts to replicate this directly have also been unsuccessful. We've observed the majority of Managed Kubernetes clusters self-healing or customers rebooting/replacing nodes to get clusters back into healthy states. We have also observed no new reports of this behavior over the last few hours. 
> 
> Our Engineering team will continue to investigate this incident and monitor for a recurrence. We will post an update once we have further information or we confirm this incident is resolved.
> 
> If you experience an issue with your Managed Kubernetes cluster, please open a ticket with our Support Team.
> Posted 39 minutes ago. Oct 09, 2023 - 17:49 UTC

Ironically that was about 10 minutes after I sent them a nastygram that their response was inadequate.

 I actually thought about trying it at 7am this morning when I saw all this was going on, but I thought no I don't want to make this problem worse for them
 
 I have new nodes that trying to provision right now.

**Comment by vmstan** [comment]
![CleanShot 2023-10-09 at 13 53 48@2x](https://github.com/vmstan/vmstio/assets/3002053/b3219b0d-5666-4b22-bbe7-66ccad12a7a0)

I have the temporary server still running to process any federation or user requests that may have cached DNS responses against that IP address, but production is active again and everything else should be online.

**Comment by vmstan** [comment]
Digital Ocean's Kubernetes platform seems to have stabilized and we have had no outages related to this in the last week.
